name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Ionic CLI
        working-directory: ./frontend
        run: npm install -g @ionic/cli

      - name: Build project
        working-directory: ./frontend
        run: ionic build -- --base-href /ProyectoPOI/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: www
          path: ./frontend/www/
      - name: Start static server and run Cypress tests
        working-directory: ./frontend
        run: |
          npm install -g http-server
          http-server ./www -p 8080 &
          npx wait-on http://localhost:8080
          npx cypress run --component --browser chrome --config baseUrl=http://localhost:8080
          npx cypress run --component --browser firefox --config baseUrl=http://localhost:8080

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run test, coverage, metrics (jest) and static analysis (eslint)
        working-directory: ./backend
        run: |
          npm run lint
          npm run test

  push-and-deploy-frontend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          name: www
          path: ./www

      - name: Build and push frontend Docker image to ACR
        run: |
          IMAGE_NAME=repodocker.azurecr.io/dah:${{ github.run_number }}
          docker build -t $IMAGE_NAME ./frontend
          echo ${{ secrets.AZURE_PASSWORD }} | docker login repodocker.azurecr.io -u ${{ secrets.AZURE_USERNAME }} --password-stdin
          docker push $IMAGE_NAME

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
          publish_branch: gh-pages

  push-and-deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=repodocker.azurecr.io/twm:${{ github.run_number }}
          docker build -t $IMAGE_NAME ./backend
          echo ${{ secrets.AZURE_PASSWORD }} | docker login repodocker.azurecr.io -u ${{ secrets.AZURE_USERNAME }} --password-stdin
          docker push $IMAGE_NAME

      - name: Deploy to Azure Web App for Containers
        run: |
          IMAGE_NAME=repodocker.azurecr.io/twm:${{ github.run_number }}
          az webapp config container set \
            --docker-custom-image-name $IMAGE_NAME \
            --docker-registry-server-password ${{ secrets.AZURE_PASSWORD }} \
            --docker-registry-server-url https://repodocker.azurecr.io \
            --docker-registry-server-user ${{ secrets.AZURE_USERNAME }} \
            --name TWM \
            --resource-group cnsa-2024-rg \